import { Recipe } from '../mobile/src/types/recipe';

export const starterRecipes: Recipe[] = [
  {
    id: 'starter-1',
    title: 'Sheet Pan Shrimp & Vegetables',
    description: 'Quick and easy one-pan meal',
    image: undefined,
    ingredients: [
      { id: '1', name: 'shrimp', amount: '1', unit: 'lb' },
      { id: '2', name: 'mushrooms', amount: '8', unit: 'oz' },
      { id: '3', name: 'olives', amount: '1/2', unit: 'cup' },
      { id: '4', name: 'olive oil', amount: '2', unit: 'tbsp' },
      { id: '5', name: 'salt', amount: '1', unit: 'tsp' },
      { id: '6', name: 'pepper', amount: '1/2', unit: 'tsp' },
      { id: '7', name: 'herbs', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Preheat oven to 200°C' },
      { id: '2', order: 2, description: 'Arrange shrimp and vegetables on pan' },
      { id: '3', order: 3, description: 'Drizzle with oil and seasonings' },
      { id: '4', order: 4, description: 'Bake for 20 minutes', duration: 20 },
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    nutrition: {
      calories: 320,
      protein: 28,
      carbs: 12,
      fats: 18,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'starter-2',
    title: 'Classic Margherita Pizza',
    description: 'Simple and delicious Italian classic',
    image: undefined,
    ingredients: [
      { id: '1', name: 'pizza dough', amount: '1', unit: 'ball' },
      { id: '2', name: 'tomato sauce', amount: '1/2', unit: 'cup' },
      { id: '3', name: 'mozzarella cheese', amount: '8', unit: 'oz' },
      { id: '4', name: 'fresh basil', amount: '10', unit: 'leaves' },
      { id: '5', name: 'olive oil', amount: '1', unit: 'tbsp' },
      { id: '6', name: 'salt', amount: '1/2', unit: 'tsp' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Preheat oven to 250°C' },
      { id: '2', order: 2, description: 'Roll out pizza dough' },
      { id: '3', order: 3, description: 'Spread tomato sauce' },
      { id: '4', order: 4, description: 'Add cheese and basil' },
      { id: '5', order: 5, description: 'Bake for 12 minutes', duration: 12 },
    ],
    prepTime: 15,
    cookTime: 12,
    servings: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'starter-3',
    title: 'Quick Stir Fry',
    description: 'Fast and healthy weeknight dinner',
    image: undefined,
    ingredients: [
      { id: '1', name: 'chicken breast', amount: '1', unit: 'lb' },
      { id: '2', name: 'broccoli', amount: '2', unit: 'cups' },
      { id: '3', name: 'carrots', amount: '2', unit: 'large' },
      { id: '4', name: 'soy sauce', amount: '3', unit: 'tbsp' },
      { id: '5', name: 'garlic', amount: '3', unit: 'cloves' },
      { id: '6', name: 'ginger', amount: '1', unit: 'tbsp' },
      { id: '7', name: 'sesame oil', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Cut chicken into strips' },
      { id: '2', order: 2, description: 'Heat pan on high' },
      { id: '3', order: 3, description: 'Cook chicken until golden' },
      { id: '4', order: 4, description: 'Add vegetables and stir fry', duration: 5 },
      { id: '5', order: 5, description: 'Add sauce and cook 2 minutes', duration: 2 },
    ],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'starter-4',
    title: 'Mediterranean Wrap',
    description: 'Fresh and flavorful wrap',
    image: undefined,
    ingredients: [
      { id: '1', name: 'tortilla', amount: '4', unit: 'large' },
      { id: '2', name: 'hummus', amount: '1/2', unit: 'cup' },
      { id: '3', name: 'cucumber', amount: '1', unit: 'large' },
      { id: '4', name: 'tomatoes', amount: '2', unit: 'medium' },
      { id: '5', name: 'feta cheese', amount: '4', unit: 'oz' },
      { id: '6', name: 'olives', amount: '1/4', unit: 'cup' },
      { id: '7', name: 'lettuce', amount: '2', unit: 'cups' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Warm tortillas' },
      { id: '2', order: 2, description: 'Spread hummus on tortilla' },
      { id: '3', order: 3, description: 'Add vegetables and cheese' },
      { id: '4', order: 4, description: 'Fold and roll tightly' },
    ],
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'starter-5',
    title: 'Vegetable Skewers',
    description: 'Perfect for grilling',
    image: undefined,
    ingredients: [
      { id: '1', name: 'zucchini', amount: '2', unit: 'medium' },
      { id: '2', name: 'bell peppers', amount: '2', unit: 'large' },
      { id: '3', name: 'mushrooms', amount: '8', unit: 'oz' },
      { id: '4', name: 'onion', amount: '1', unit: 'large' },
      { id: '5', name: 'olive oil', amount: '3', unit: 'tbsp' },
      { id: '6', name: 'herbs', amount: '2', unit: 'tbsp' },
      { id: '7', name: 'lemon', amount: '1', unit: 'whole' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Cut vegetables into chunks' },
      { id: '2', order: 2, description: 'Thread onto skewers' },
      { id: '3', order: 3, description: 'Brush with oil and herbs' },
      { id: '4', order: 4, description: 'Grill for 10 minutes', duration: 10 },
      { id: '5', order: 5, description: 'Squeeze lemon before serving' },
    ],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'starter-6',
    title: 'One-Pot Pasta',
    description: 'Minimal cleanup required',
    image: undefined,
    ingredients: [
      { id: '1', name: 'pasta', amount: '12', unit: 'oz' },
      { id: '2', name: 'cherry tomatoes', amount: '2', unit: 'cups' },
      { id: '3', name: 'garlic', amount: '4', unit: 'cloves' },
      { id: '4', name: 'basil', amount: '1/2', unit: 'cup' },
      { id: '5', name: 'olive oil', amount: '2', unit: 'tbsp' },
      { id: '6', name: 'vegetable broth', amount: '4', unit: 'cups' },
      { id: '7', name: 'parmesan cheese', amount: '1/2', unit: 'cup' },
    ],
    steps: [
      { id: '1', order: 1, description: 'Combine pasta and tomatoes in pot' },
      { id: '2', order: 2, description: 'Add broth and bring to boil' },
      { id: '3', order: 3, description: 'Simmer for 12 minutes', duration: 12 },
      { id: '4', order: 4, description: 'Stir in basil and cheese' },
    ],
    prepTime: 5,
    cookTime: 12,
    servings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

